# path of URL to sample sheet(TSV format, columns: sample, condition, ...)
samples: config/sample_sheet.tsv

# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2,
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the
# same biological sample).If the column "strandedness" is present (which is optional),
# can be empty or has one of these values: none, yes or reverse. none is for unstranded
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse`
# which is referenced in STAR manual section 7, "Counting number of reads per gene".
units: config/units.tsv

trimming:
  # skip trimming: false or true
  skip: False
  # the sequencing adapter
  adapter: ""

ref:
  # Ensembl species name
  species: rattus_norvegicus
  # Ensembl release
  release: 110
  # Ensembl assembly
  assembly: mRatBN7.2
  g2n: resources/biomart.Rnor.tsv
  
index: 
  activate: False
  location: /home/light/references/salmon_indices/rat/mRatBN7.2.ensembl_v110_addFP


pca:
  activate: True
  # Per default, a separate PCA plot is generated for each of the
  # `variables_of_interest` and the `batch_effects`, coloring according to
  # that variables groups.
  # If you want PCA plots for further columns in the samples.tsv sheet, you
  # can request them under labels as a list, for example:
  # - relatively_uninteresting_variable_X
  # - possible_batch_effect_Y
  labels:
    - group
    
topGenes-plot:
  # set the variable from the sample sheet to use for grouping on x-axis in plot
  grouping-var: "group"
  # set the variable from  the sample sheet to use for coloring the samples  in plots
  # normally set to the same variable as grouping
  color-var: 

diffexp:
  # set the threshold to filter out uninformative genes
  prefilter:
    # counts for each gene (row) are summed and all rowsums below the threhsold
    # are filtered out
    threshold: 10
    # give custom formula which is not rowSums to filter out uninformative genes 
    custom:
  # variables for whome you are interested in whether they have an effect on
  # expression levels
  # significance level to use for volcano, ma- and qq-plots
  generate-contrasts: False
  sig-level:
    diffexp: 0.05
    volcano-plot: 0.05
  variables_of_interest:
    sample.group:
      # any fold change will be relative to this factor level
      base_level: R
    tissue:
      base_level: blood
  # variables whose effect you want to model to separate them from your
  # variables_of_interest
  batch_effects:
  # contrasts for the deseq2 results method to determine fold changes
  # contrasts:
  #   A-vs-B_treatment_1:
  #     # must be one of the variables_of_interest, for details see:
  #     # https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#contrasts
  #     variable_of_interest: treatment_1
  #     # must be a level present in the variable_of_interest that is not the
  #     # base_level specified above
  #     level_of_interest: A
  # The default model includes all interactions among variables_of_interest
  # and batch_effects added on. For the example above this implicitly is:
  # model: ~jointly_handled + treatment_1 * treatment_2
  # For the default model to be used, simply specify an empty `model: ""` below.
  # If you want to introduce different assumptions into your model, you can
  # specify a different model to use, for example skipping the interaction:
  # model: ~jointly_handled + treatment_1 + treatment_2
  model: ~group

    # contrasts for the deseq2 results method
  contrasts:
    # arbitrary-name:
    #    - columnname
    #    - effect1      # positive log2FC indicate upgregulated in this group
    #    - effect2      # negative log2FC indicate higher expression in this group
    M.ctx-vs-R.ctx:
      - group
      - M.ctx
      - R.ctx
    M.blood-vs-R.blood:
      - group
      - M.blood
      - R.blood

enrichment:
  fgsea:
    # tool is only run if set to `true`
    activate: True
    # specify the column used for the ranking of genes. If set to "rank", ranking metric will be calculated as sign(log2Foldchange) * -log10(pvalue)
    ranking_metric: "log2FoldChange"
    GO:
      # run fgsea with using Gene Ontology database. will run if set to "true"
      activate: true
      # specify the GO domain to use for the GSEA: can be one of: Biological process (GO:BP), cellular component (GO:CC), molecular function (GO:MF)
      GO_domain: "GO:BP"
    MSigDB:
      # run fgsea with using MSigDb gene set. will run if set to "true"
      activate: True
      # Specify gene set category for GSEA. Example "H" for Hallmark gene set
      category: "H"
      # Optional: Specify gene set subcategory for GSEA. Example "CP" or "CP:KEGG" for sub- and subsubcategories of C2 gene set
      subcategory: 
      # Custom or downloaded gene sets can also be provided for GSEA. File need to be in .gmt format
      gene_sets_file: 
    fdr_gene_set: 0.05
    # minimum achievable p-value  (equivalent to the reciprocal of the number of permutations, see fgsea docs)
    eps: 1.0e-50

params:
  fastqc: ""
  salmon: ""
  multiqc: ""
