# path of URL to sample sheet(TSV format, columns: sample, condition, ...)
samples: config/sample_sheet.tsv

# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2,
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the
# same biological sample).If the column "strandedness" is present (which is optional),
# can be empty or has one of these values: none, yes or reverse. none is for unstranded
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse`
# which is referenced in STAR manual section 7, "Counting number of reads per gene".
units: config/units.tsv

trimming:
  # skip trimming: false or true
  skip: False
  # the sequencing adapter
  adapter: ACGGATCGATCGATCGATCGAT

ref:
  # Ensembl species name
  species: rattus_norvegicus
  # Ensembl release
  release: 110
  # Genome build
  build: mRatBN7.2
  
index: 
  activate: False
  location: /home/light/references/salmon_indices/rat/mRatBN7.2.ensembl_v110


pca:
  activate: True
  # Per default, a separate PCA plot is generated for each of the
  # `variables_of_interest` and the `batch_effects`, coloring according to
  # that variables groups.
  # If you want PCA plots for further columns in the samples.tsv sheet, you
  # can request them under labels as a list, for example:
  # - relatively_uninteresting_variable_X
  # - possible_batch_effect_Y
  labels:
    ""

diffexp:
  # variables for whome you are interested in whether they have an effect on
  # expression levels
  variables_of_interest:
    sample.group:
      # any fold change will be relative to this factor level
      base_level: ctrl
  # variables whose effect you want to model to separate them from your
  # variables_of_interest
  batch_effects:
  # contrasts for the deseq2 results method to determine fold changes
  # contrasts:
  #   A-vs-B_treatment_1:
  #     # must be one of the variables_of_interest, for details see:
  #     # https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#contrasts
  #     variable_of_interest: treatment_1
  #     # must be a level present in the variable_of_interest that is not the
  #     # base_level specified above
  #     level_of_interest: A
  # The default model includes all interactions among variables_of_interest
  # and batch_effects added on. For the example above this implicitly is:
  # model: ~jointly_handled + treatment_1 * treatment_2
  # For the default model to be used, simply specify an empty `model: ""` below.
  # If you want to introduce different assumptions into your model, you can
  # specify a different model to use, for example skipping the interaction:
  # model: ~jointly_handled + treatment_1 + treatment_2
  model: ""

    # contrasts for the deseq2 results method
  contrasts:
    # arbitrary-name:
    #    - columnname
    #    - effect1
    #    - effect2
    ctrl-vs-normoxic:
      - sample.group
      - ctrl
      - normoxic
    normoxic-vs-hypoxic:
      - sample.group
      - normoxic
      - hypoxic
    ctr-vs-hypoxic:
      - sample.group
      - ctrl
      - hypoxic

params:
  fastqc: ""
  salmon: ""
  multiqc: ""
