# path of URL to sample sheet(TSV format, columns: sample, condition, ...)
samples: config/sample_sheet.tsv

ref:
  # Ensembl species name
  species: rattus_norvegicus
  # Ensembl release
  release: 110
  # Genome build
  build: mRatBN7.2
  
index: 
  activate: False
  location: /home/haberl/references/salmon_indices/rat/mRatBN7.2.ensembl_v110

pca:
  activate: True
  # Per default, a separate PCA plot is generated for each of the
  # `variables_of_interest` and the `batch_effects`, coloring according to
  # that variables groups.
  # If you want PCA plots for further columns in the samples.tsv sheet, you
  # can request them under labels as a list, for example:
  # - relatively_uninteresting_variable_X
  # - possible_batch_effect_Y
  labels: ""

params:
  fastqc: ""
  salmon: ""
  multiqc: ""
